name: CD - Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: your-vercel-org-id  # From Vercel dashboard
          vercel-project-id: your-vercel-project-id  # From Vercel
          scope: your-vercel-team-slug  # If team account
          vercel-args: '--prod'  # For production deploy